import React from 'react';
import Feature from '../../components/feature/Feature';
import './whatsw.css';

const WhatSW = () => (
  <div className="sw__whatsw section__margin" id="wsw">
    <div className="sw__whatsw-feature">
      <Feature title="What is Sneaker World" text="We so opinion friends me message as delight. Whole front do of plate heard oh ought. His defective nor convinced residence own. Connection has put impossible own apartments boisterous. At jointure ladyship an insisted so humanity he. Friendly bachelor entrance to on by." />
    </div>
    <div className="sw__whatsw-heading">
      <h1 className="gradient__text">The possibilities are beyond your imagination</h1>
      <p>Explore the Library</p>
    </div>
    <div className="sw__whatsw-container">
      <Feature title="Full paintjob" text="Sneakers paintjob is the process of customizing your shoes with paint. It is a fun activity to express your creativity through a unique and one-of-a-kind footwear. It is a great way to show off your individual style without breaking the bank. To get started with your own sneaker paintjob, you will need to prepare your shoes. Start by cleaning your sneakers and lightly sanding them to give the paint a better surface to adhere to. Next, apply a base coat of paint before adding a few coats of your chosen color. For an extra personal touch, you can use tape to create shapes or patterns. When all the paint jobs are finished, you can use a sealant or a protective spray to make it last longer. With a bit of patience and creativity, you can transform any ordinary pair of kicks into a work of art." />
      <Feature title="Printing" text="Printing on sneakers has become increasingly popular in recent years. It allows for a whole new level of creativity and customization, allowing you to express yourself in a completely unique way. It’s become especially popular for streetwear enthusiasts who want to make a statement. There are a few ways to print on sneakers. Direct-to-garment printing is the most widely used technique. This process is relatively simple; by running a digital garment printer, the design is printed directly onto the material of the sneakers. Another method is using heat transfer vinyl. This process is a bit more complicated as it requires additional materials — such as a vinyl cutting machine and a heat press — and more time to apply the design to the shoes. Printing on sneakers with this technique requires creating a design, cutting it out of vinyl with a machine, applying it with heat, and finally pressing it onto the sneaker. A third method for printing on sneakers involves using inkjet transfers. This process is relatively straightforward, as it requires the use of an inkjet printer and special transfer paper to achieve the desired results. With this technique, you can create designs with images, words, and more that can easily be transferred to sneakers. No matter which technique you choose, printing on sneakers is an excellent way to customize your wardrobe and express yourself." />
      <Feature title="Full restoration" text="Sneakers full restoration is one of the most useful services that any sneaker enthusiast can take advantage of. Restoring a pair of sneakers can bring about a much needed breath of fresh air for any individual that wants to keep their favorite pairs of shoes looking as close to new as possible. With the help of sneaker restoration services, any individual can have their old pairs of shoes looking as good as when they first stepped out of the store. Sneaker restoration services, like most services, come in different forms. Depending on the type of shoes that need to be restored, the service may simply involve a deep clean or a shoe repair, to a full-on restoration of the exterior and interior of the shoes. In the full restoration service, the service provider will start by inspecting the exterior of the shoes to detect any damages or imperfections, such as scuffs or cracks in the material. Once the assessment is completed, they will begin restoring the outer layer, which usually involves applying a new product to the outer material to restore its original look. After the outer layer has been restored, the service provider will then restore the inner layer of the shoes. This process may involve the use of a special cleaning solution to remove any marks or stains on the inner layer, as well as recovering any missing padding or cushioning material in the shoes. Once the shoes have been fully restored, they are given a fresh shine, which makes them look almost new. With the help of a professional sneaker restoration service, anyone can make their old shoes look as good as new. The process may be a bit time consuming, but it will definitely be worth it in the end." />
    </div>
  </div>
);

export default WhatSW;